export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST"
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const CART_DELETE_ITEMS = "CART_DELETE_ITEMS"
