export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST"
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"
export const CART_DELETE_ITEMS = "CART_DELETE_ITEMS"

export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD"
