export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_LIST_ALL_REQUEST = "PRODUCT_LIST_ALL_REQUEST"
export const PRODUCT_LIST_ALL_SUCCESS = "PRODUCT_LIST_ALL_SUCCESS"
export const PRODUCT_LIST_ALL_FAIL = "PRODUCT_LIST_ALL_FAIL"

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL"
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET"
