export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_LIST_ALL_REQUEST = "PRODUCT_LIST_ALL_REQUEST"
export const PRODUCT_LIST_ALL_SUCCESS = "PRODUCT_LIST_ALL_SUCCESS"
export const PRODUCT_LIST_ALL_FAIL = "PRODUCT_LIST_ALL_FAIL"
export const PRODUCT_LIST_ALL_RESET = "PRODUCT_LIST_ALL_RESET"

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST"
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS"
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL"
export const PRODUCT_DELETE_RESET = "PRODUCT_DELETE_RESET"

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST"
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS"
export const PRODUCT_CREATE_FAIL = "PRODUCT_CREATE_FAIL"
export const PRODUCT_CREATE_RESET = "PRODUCT_CREATE_RESET"

export const PRODUCT_IMAGE_UPLOAD_REQUEST = "PRODUCT_IMAGE_UPLOAD_REQUEST"
export const PRODUCT_IMAGE_UPLOAD_SUCCESS = "PRODUCT_IMAGE_UPLOAD_SUCCESS"
export const PRODUCT_IMAGE_UPLOAD_FAIL = "PRODUCT_IMAGE_UPLOAD_FAIL"
export const PRODUCT_IMAGE_UPLOAD_RESET = "PRODUCT_IMAGE_UPLOAD_RESET"
