export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL"
export const USER_UPDATE_RESET = "USER_UPDATE_RESET"

export const USER_LIST_ALL_REQUEST = "USER_LIST_ALL_REQUEST"
export const USER_LIST_ALL_SUCCESS = "USER_LIST_ALL_SUCCESS"
export const USER_LIST_ALL_FAIL = "USER_LIST_ALL_FAIL"
export const USER_LIST_ALL_RESET = "USER_LIST_ALL_RESET"

export const USER_UPDATE_ADMIN_REQUEST = "USER_UPDATE_ADMIN_REQUEST"
export const USER_UPDATE_ADMIN_SUCCESS = "USER_UPDATE_ADMIN_SUCCESS"
export const USER_UPDATE_ADMIN_FAIL = "USER_UPDATE_ADMIN_FAIL"
export const USER_UPDATE_ADMIN_RESET = "USER_UPDATE_ADMIN_RESET"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"
export const USER_DELETE_RESET = "USER_DELETE_RESET"
